const requirementCatalog = [
  {
    code: 'REQ-01',
    order: 1,
    title: 'Executive Dashboard',
    category: 'Operations',
    status: 'core',
    description: 'High-level KPI and decision dashboard for organizational asset health and utilization.',
    items: [
      'Total assets',
      'Active / inactive assets',
      'Assets under maintenance',
      'Critical assets',
      'Asset value',
      'Asset utilization %',
      'Asset health %',
      'Upcoming maintenance',
      'Overdue maintenance',
      'Warranty expiry',
      'AMC / contract expiry',
      'Depreciation',
      'Purchase vs current value',
      'Total maintenance cost',
      'Department-wise assets',
      'Location-wise assets',
      'Real-time alerts',
      'AI-generated recommendations',
    ],
  },
  {
    code: 'REQ-02',
    order: 2,
    title: 'Asset Master',
    category: 'Asset Registry',
    status: 'core',
    description: 'A complete digital profile for each asset across its lifecycle.',
    items: [
      'Asset ID',
      'QR code',
      'Barcode',
      'RFID',
      'Asset name',
      'Asset category',
      'Subcategory',
      'Manufacturer',
      'Model',
      'Serial number',
      'Purchase date',
      'Purchase price',
      'Current value',
      'Supplier',
      'Invoice number',
      'Warranty',
      'AMC',
      'Department',
      'Building',
      'Floor',
      'Room',
      'Responsible employee',
      'Asset status',
      'Asset condition',
      'Criticality',
      'Documents',
      'Photos',
      'Manuals',
      'Service history',
      'Maintenance history',
      'Transfer history',
      'Disposal history',
    ],
  },
  {
    code: 'REQ-03',
    order: 3,
    title: 'Asset Lifecycle Management',
    category: 'Lifecycle',
    status: 'core',
    description: 'Track the complete lifecycle from planning to disposal.',
    items: [
      'Planning',
      'Purchase',
      'Receiving',
      'Installation',
      'Allocation',
      'Operation',
      'Maintenance',
      'Transfer',
      'Upgrade',
      'Retirement',
      'Disposal',
    ],
  },
  {
    code: 'REQ-04',
    order: 4,
    title: 'QR / Barcode / RFID',
    category: 'Asset Identification',
    status: 'core',
    description: 'Unique digital identity and scan-driven asset operations.',
    items: [
      'Scan asset → open asset profile',
      'Asset action shortcuts',
      'Report issue',
      'Request maintenance',
      'Transfer',
      'View history',
      'Verify asset',
      'Upload photo',
      'Mark missing',
      'RFID tagging',
      'RFID gate scanning',
      'Bulk verification',
      'Automated inventory',
      'Unauthorized movement detection',
    ],
  },
  {
    code: 'REQ-05',
    order: 5,
    title: 'AI Asset Assistant',
    category: 'AI & Intelligence',
    status: 'advanced',
    description: 'Conversational asset intelligence and decision support.',
    items: [
      'Natural language queries',
      'Replacement recommendations',
      'Costly maintenance analysis',
      'High-loss department detection',
      'Monthly expiry analysis',
      'Failure risk prediction',
      'Replacement planning',
      'Unassigned asset search',
      'Building-based filtering',
      'Audit report generation',
    ],
  },
  {
    code: 'REQ-06',
    order: 6,
    title: 'Asset Health Score',
    category: 'Performance',
    status: 'core',
    description: 'Dynamic health scoring for key assets.',
    items: [
      'Performance',
      'Maintenance',
      'Age',
      'Failure risk',
      'Usage',
      'Excellent / Healthy / Attention Required / High Risk / Critical levels',
    ],
  },
  {
    code: 'REQ-07',
    order: 7,
    title: 'Predictive Maintenance',
    category: 'Maintenance',
    status: 'advanced',
    description: 'Predict failure risk and trigger proactive maintenance plans.',
    items: [
      'Historical maintenance analysis',
      'Failure history review',
      'Usage hours tracking',
      'Sensor data correlation',
      'Temperature and vibration monitoring',
      'Power and error log analysis',
      'Age and operating condition scoring',
      'Predictive maintenance alert generation',
    ],
  },
  {
    code: 'REQ-08',
    order: 8,
    title: 'Maintenance Management',
    category: 'Maintenance',
    status: 'core',
    description: 'Support for different maintenance types and repeated service workflows.',
    items: [
      'Preventive',
      'Predictive',
      'Corrective',
      'Breakdown',
      'Emergency',
      'Condition-based',
      'Calibration',
      'Inspection',
      'Maintenance work order lifecycle',
    ],
  },
  {
    code: 'REQ-09',
    order: 9,
    title: 'Automated Maintenance Scheduling',
    category: 'Planning',
    status: 'core',
    description: 'Automatically schedule next maintenance with resource allocation.',
    items: [
      'Next maintenance date',
      'Technician assignment',
      'Required spare parts',
      'Estimated duration',
      'Estimated cost',
      'Priority assignment',
      'Calendar view',
    ],
  },
  {
    code: 'REQ-10',
    order: 10,
    title: 'Work Order Management',
    category: 'Maintenance Operations',
    status: 'core',
    description: 'Operational work order execution from assignment to approval.',
    items: [
      'Work order issuance',
      'Asset details',
      'Location details',
      'Problem record',
      'Previous service history',
      'Tools needed',
      'Spare parts list',
      'SOP and checklist',
      'Accept / start / pause / complete workflow',
      'Image and note upload',
      'Parts used and labor tracking',
      'Approval workflow',
    ],
  },
  {
    code: 'REQ-11',
    order: 11,
    title: 'Mobile Technician Portal',
    category: 'Field Operations',
    status: 'advanced',
    description: 'Mobile-first technician UX for field execution and digital checklists.',
    items: [
      'PWA / mobile-first portal',
      'QR scanning',
      'Camera support',
      'GPS location capture',
      'Offline mode',
      'Voice notes',
      'Digital checklist',
      'Digital signature',
      'Photo upload',
      'Work timer',
      'Push notifications',
    ],
  },
  {
    code: 'REQ-12',
    order: 12,
    title: 'Inventory & Spare Parts',
    category: 'Inventory',
    status: 'core',
    description: 'Stock control for spare parts, consumables, tools, and warehouse movement.',
    items: [
      'Spare parts',
      'Consumables',
      'Tools',
      'Stock tracking',
      'Minimum stock',
      'Maximum stock',
      'Warehouse detail',
      'Bin location',
      'Stock movement',
      'Purchase requests',
      'Issue and return',
      'Consumption tracking',
      'Low-stock alerts',
    ],
  },
  {
    code: 'REQ-13',
    order: 13,
    title: 'Procurement',
    category: 'Procurement',
    status: 'core',
    description: 'Structured purchase lifecycle from request to payment completion.',
    items: [
      'Maintenance requirement',
      'Purchase request',
      'Approval',
      'Quotation',
      'Purchase order',
      'Goods received',
      'Asset created',
      'Invoice',
      'Payment',
    ],
  },
  {
    code: 'REQ-14',
    order: 14,
    title: 'Vendor Management',
    category: 'Supplier Management',
    status: 'core',
    description: 'Vendor performance, contract and service oversight for all external partners.',
    items: [
      'Vendor ID',
      'Company',
      'Contact',
      'GST',
      'Products',
      'Contracts',
      'AMC',
      'SLA',
      'Performance',
      'Rating',
      'Payment history',
      'Service history',
      'Vendor scorecard',
    ],
  },
  {
    code: 'REQ-15',
    order: 15,
    title: 'AMC / Warranty Management',
    category: 'Contract Management',
    status: 'core',
    description: 'Monitor service and support contracts and renewals.',
    items: [
      'Warranty start',
      'Warranty end',
      'AMC start',
      'AMC end',
      'Contract value',
      'SLA',
      'Vendor',
      'Renewal date',
      'Automatic expiry notifications',
    ],
  },
  {
    code: 'REQ-16',
    order: 16,
    title: 'Asset Transfer',
    category: 'Asset Movement',
    status: 'core',
    description: 'Track transfers through approval and custody chain.',
    items: [
      'Transfer request',
      'Manager approval',
      'IT approval',
      'Employee reassignment',
      'Chain of custody tracking',
    ],
  },
  {
    code: 'REQ-17',
    order: 17,
    title: 'Asset Check-In / Check-Out',
    category: 'Asset Movement',
    status: 'core',
    description: 'Issue and return items such as laptops, tools, vehicles and lab equipment.',
    items: [
      'Laptops',
      'Projectors',
      'Cameras',
      'Tools',
      'Vehicles',
      'Lab equipment',
      'Issued to',
      'Issue date',
      'Expected return',
      'Condition tracking',
    ],
  },
  {
    code: 'REQ-18',
    order: 18,
    title: 'Asset Audit',
    category: 'Compliance',
    status: 'core',
    description: 'Create and track asset audit campaigns across large inventories.',
    items: [
      'Periodic audit campaigns',
      'Verified count',
      'Missing count',
      'Damaged count',
      'Unverified count',
      'QR / Barcode / RFID verification',
      'Mobile scanning',
      'GPS',
      'Photo capture',
    ],
  },
  {
    code: 'REQ-19',
    order: 19,
    title: 'Lost / Missing Asset Detection',
    category: 'Risk & Security',
    status: 'core',
    description: 'Identify missing, misplaced or suspicious asset movement.',
    items: [
      'Missing assets',
      'Unassigned assets',
      'Wrong-location assets',
      'Duplicate assets',
      'Unauthorized transfers',
      'Long-unused assets',
    ],
  },
  {
    code: 'REQ-20',
    order: 20,
    title: 'Digital Twin',
    category: 'Advanced Monitoring',
    status: 'advanced',
    description: 'Represent critical assets as digital component models with health and maintenance histories.',
    items: [
      'Component representation',
      'Engine / battery / fuel mapping',
      'Health scoring',
      'Sensor data',
      'Maintenance history',
      'Failure history',
    ],
  },
  {
    code: 'REQ-21',
    order: 21,
    title: 'IoT Integration',
    category: 'Connected Assets',
    status: 'advanced',
    description: 'Connect telemetry devices to asset health and alerting workflows.',
    items: [
      'IoT sensor input',
      'MQTT pipeline',
      'Analytics engine',
      'Temperature',
      'Humidity',
      'Vibration',
      'Voltage',
      'Current',
      'Pressure',
      'RPM',
      'Energy consumption',
      'Location tracking',
    ],
  },
  {
    code: 'REQ-22',
    order: 22,
    title: 'Real-Time Asset Monitoring',
    category: 'Monitoring',
    status: 'advanced',
    description: 'Live health and status overview for active physical assets.',
    items: [
      'Live asset status board',
      'Normal / Warning / Critical states',
      'Click-through telemetry',
      'Operational visibility',
    ],
  },
  {
    code: 'REQ-23',
    order: 23,
    title: 'AI Anomaly Detection',
    category: 'AI & Intelligence',
    status: 'advanced',
    description: 'Identify unusual operating patterns before assets fail.',
    items: [
      'Temperature anomaly detection',
      'Performance threshold alerts',
      'Anomaly summary cards',
      'Risk prioritization',
    ],
  },
  {
    code: 'REQ-24',
    order: 24,
    title: 'Energy Management',
    category: 'Sustainability',
    status: 'advanced',
    description: 'Track energy consumption and improve operational efficiency.',
    items: [
      'Electricity consumption',
      'Fuel',
      'Water',
      'Gas',
      'Energy cost',
      'Asset efficiency',
      'Carbon footprint',
      'Potential savings',
    ],
  },
  {
    code: 'REQ-25',
    order: 25,
    title: 'GIS / Map-Based Asset Management',
    category: 'Spatial Visibility',
    status: 'advanced',
    description: 'Show asset distribution across campuses, plants and multiple branches.',
    items: [
      'Map-based asset display',
      'Multiple building locations',
      'Campus and branch visibility',
      'Infrastructure monitoring',
    ],
  },
  {
    code: 'REQ-26',
    order: 26,
    title: 'Role-Based Access Control',
    category: 'Security',
    status: 'core',
    description: 'Restrict access according to responsibility and role boundaries.',
    items: [
      'Super Admin',
      'Asset Manager',
      'Maintenance Manager',
      'Technician',
      'Department Manager',
      'Finance',
      'Auditor',
      'Employee',
      'Vendor',
    ],
  },
  {
    code: 'REQ-27',
    order: 27,
    title: 'Approval Engine',
    category: 'Governance',
    status: 'core',
    description: 'Configurable approval workflows for operational transactions.',
    items: [
      'Asset purchase',
      'Asset transfer',
      'Disposal',
      'Repair',
      'Replacement',
      'Procurement',
      'AMC renewal',
      'Multi-level approval',
    ],
  },
  {
    code: 'REQ-28',
    order: 28,
    title: 'Notifications',
    category: 'Communication',
    status: 'core',
    description: 'Multi-channel alerts for time-sensitive events and operational reminders.',
    items: [
      'Web notification',
      'Email',
      'SMS',
      'WhatsApp',
      'Push notification',
      'Maintenance due',
      'Warranty expiry',
      'Asset health alert',
      'Work order overdue',
    ],
  },
  {
    code: 'REQ-29',
    order: 29,
    title: 'Document Management',
    category: 'Records',
    status: 'core',
    description: 'Centralize all asset-related documentation and certificates.',
    items: [
      'Invoice',
      'Purchase order',
      'Warranty',
      'AMC',
      'Manual',
      'Certificate',
      'Inspection report',
      'Calibration certificate',
      'Photos',
      'Videos',
    ],
  },
  {
    code: 'REQ-30',
    order: 30,
    title: 'Financial Asset Management',
    category: 'Finance',
    status: 'core',
    description: 'Monitor asset cost and ownership value across the asset lifecycle.',
    items: [
      'Purchase cost',
      'Installation cost',
      'Maintenance cost',
      'Depreciation',
      'Current book value',
      'Salvage value',
      'Total ownership cost',
      'Replacement cost',
      'TCO analysis',
    ],
  },
  {
    code: 'REQ-31',
    order: 31,
    title: 'Asset Replacement Intelligence',
    category: 'AI & Finance',
    status: 'advanced',
    description: 'Recommend replacement based on cost, risk and business value.',
    items: [
      'Age analysis',
      'Maintenance cost comparison',
      'Failure risk review',
      'Current value',
      'Replacement cost',
      'Recommendation engine',
    ],
  },
  {
    code: 'REQ-32',
    order: 32,
    title: 'Disposal Management',
    category: 'Lifecycle',
    status: 'core',
    description: 'Govern end-of-life asset disposal through inspection and approval.',
    items: [
      'Disposal request',
      'Inspection',
      'Approval',
      'Auction / Scrap / Donation',
      'Financial closure',
      'Asset retirement',
    ],
  },
  {
    code: 'REQ-33',
    order: 33,
    title: 'Advanced Analytics',
    category: 'Analytics',
    status: 'core',
    description: 'Operational and financial analytics for asset performance improvement.',
    items: [
      'Asset utilization',
      'Asset availability',
      'MTBF',
      'MTTR',
      'OEE',
      'Maintenance cost',
      'Failure rate',
      'Downtime',
      'Technician performance',
      'Vendor performance',
      'Asset ROI',
      'TCO',
      'Inventory turnover',
    ],
  },
  {
    code: 'REQ-34',
    order: 34,
    title: 'AI Reports',
    category: 'AI & Reporting',
    status: 'advanced',
    description: 'Generate business-ready insights from natural-language prompts.',
    items: [
      'Top 20 expensive assets',
      'Table generation',
      'Graph generation',
      'Analysis',
      'Recommendations',
      'PDF / Excel export',
    ],
  },
  {
    code: 'REQ-35',
    order: 35,
    title: 'Natural Language Search',
    category: 'AI & Search',
    status: 'advanced',
    description: 'Translate natural-language queries into asset search and report logic.',
    items: [
      'Natural language filters',
      'Intent-to-query conversion',
      'Contextual result display',
    ],
  },
  {
    code: 'REQ-36',
    order: 36,
    title: 'Voice Commands',
    category: 'Hands-Free Ops',
    status: 'advanced',
    description: 'Enable technicians to trigger actions without navigating the UI.',
    items: [
      'Start maintenance command',
      'Report issue command',
      'Pending work orders query',
    ],
  },
  {
    code: 'REQ-37',
    order: 37,
    title: 'Computer Vision',
    category: 'AI & Vision',
    status: 'advanced',
    description: 'Analyze uploaded asset images and identify equipment and condition.',
    items: [
      'Asset type detection',
      'Visible damage detection',
      'Serial number recognition',
      'Model detection',
      'Label detection',
      'Condition assessment',
    ],
  },
  {
    code: 'REQ-38',
    order: 38,
    title: 'Cybersecurity',
    category: 'Security',
    status: 'core',
    description: 'Enterprise security controls protecting the platform and asset data.',
    items: [
      'MFA',
      'SSO',
      'RBAC',
      'JWT / OAuth',
      'Session management',
      'Encryption',
      'Audit logs',
      'IP / device monitoring',
      'Login alerts',
      'API security',
      'Rate limiting',
      'Data backup',
      'Disaster recovery',
    ],
  },
];

function buildRequirementSummary(items = requirementCatalog) {
  const totalGroups = items.length;
  const totalChecklistItems = items.reduce((sum, item) => sum + item.items.length, 0);
  const coreCount = items.filter((item) => item.status === 'core').length;
  const advancedCount = items.filter((item) => item.status === 'advanced').length;

  return {
    totalGroups,
    totalChecklistItems,
    coreCount,
    advancedCount,
    coveragePct: Math.round((coreCount / Math.max(totalGroups, 1)) * 100),
  };
}

module.exports = { requirementCatalog, buildRequirementSummary };
